---
deployment:
  tasks:
    - export DEPLOYPATH=/home/livenets/maps.livenetstudios.co.za/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/rm -f $DEPLOYPATH/.htaccess
    - /bin/rm -f $DEPLOYPATH/.env
    - /bin/cp -R dist/* $DEPLOYPATH